Implement the kmedoids dijkstra algorithm for the gas sector
openego/eTraGo pull request #485
Opened 2022-08-22 06:25 UTC by fwitte

To make use of the implemented algorithm, I splitted the methods defined in the former "networkclustering.py", which was separated into etrago/cluster/spatial and etrago/cluster/electrical. etrago/cluster/gas will make use of the methods in etrago/cluster/spatial.

Also, it seems that some preprocessing and postprocessing steps are identical for the different algorithms, so we should make use of that fact and reduce lines of code.

2022-08-25 09:01 UTC, fwitte commented
@pieterhexen and @ClaraBuettner: The name of this PR + branch is currently not really correct, please ignore that.

I made a first draft to structure the clustering methods:

- sector specific preprocessing
- clustering
- sectorspecific postprocessing

I tested the implementation, it produces identical results for dev branch and this branch for both electrical and gas system. The kmedoids clustering for the gas system is not yet implemented here, but we might want to move this to dev already, because it makes a lot of things much clearer, I think.

What is your opinion about it?

Thank you! :)

2022-08-26 08:10 UTC, pieterhexen requested changes
Checked code and tested on test_dump. Everything works fine.

2022-08-26 08:40 UTC, fwitte commented on etrago/appl.py
> +        "random_state": 123456,  # random state for replicability of kmeans results
Critical issue resolved by [ee0bddd](https://github.com/openego/eTraGo/pull/485/commits/ee0bdddeee537d28b16c08eedee03fb1a3a1458f), thank you!

2022-08-31 12:20 UTC, CarlosEpia commented
Hi @fwitte. I see big changes in this PR, therefore it would be nice if you could merge dev into this branch and check if it works correctly together with the last changes in dev. Additionally, can you describe briefly the changes you did? Since the history of electrical.py is not available, that description would help me to choose what parts of the code review more carefully.

2022-09-01 07:40 UTC, CarlosEpia commented
I just tried to run this branch using the eHV clustering and ran into this error message:

  File "/home/student/git/eTraGo/etrago/appl.py", line 513, in <module>
    etrago = run_etrago(args, json_path=None)

  File "/home/student/git/eTraGo/etrago/appl.py", line 475, in run_etrago
    etrago.ehv_clustering()

  File "/home/student/git/eTraGo/etrago/cluster/electrical.py", line 361, in ehv_clustering
    busmap = busmap_from_psql(self)

NameError: name 'busmap_from_psql' is not defined

2022-09-02 08:10 UTC, fwitte commented
@CarlosEpia: Are you available today?

2022-09-02 08:15 UTC, CarlosEpia commented
> @CarlosEpia: Are you available today?

Yeah, sure. If it is ok for you, we can meet in the Jitsi room at 11:00.

2022-09-02 10:06 UTC, CarlosEpia commented
@fwitte according to our meeting, I will check this PR as soon as possible. Since the purpose of this branch is different from its original issue, could you create a new issue to describe the problem that this PR is solving? It is just for traceability.

2022-09-02 12:09 UTC, fwitte commented
Okay, everything ready here, @pieterhexen and @CarlosEpia, there is also a respective issue #492

2022-09-02 13:32 UTC, CarlosEpia approved these changes
This branch is apparently working as expected. I ran eHV and Dijktra clustering successfully using the test case and full dataset. It can be merged after updating the parameters' description in appl.py

2022-09-02 13:32 UTC, CarlosEpia commented on etrago/appl.py
> +        "method_gas": "kmeans",  # choose clustering method: kmeans or kmedoids-dijkstra
Please update the description of the parameters that were changed in this PR

2022-09-05 05:48 UTC, fwitte commented
> apparently

:D

> It can be merged after updating the parameters' description in appl.py

Updated the description, you can merge it @pieterhexen or @CarlosEpia

2022-09-05 07:55 UTC, CarlosEpia commented
> > apparently
> 
> :D
> 
> > It can be merged after updating the parameters' description in appl.py
> 
> Updated the description, you can merge it @pieterhexen or @CarlosEpia

Hi @pieterhexen does it make sense for you if you merge this branch since I can see that #493  is also approved?

2022-09-05 08:17 UTC, merged

2022-09-05 08:20 UTC, pieterhexen commented
> Hi @pieterhexen does it make sense for you if you merge this branch since I can see that #493 is also approved?

Hey Carlos, I'll merge the change in #493 later because it is not a bug and this branch doesn't change the behaviour of the clustering.